Vats:
  type: entity
  table: vats
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 1
      fixed: false
      nullable: false
    value:
      type: float
      nullable: false
  lifecycleCallbacks: {  }
